In [54]:
import pandas as pd
import datasets
from huggingface_hub import hf_hub_download, list_repo_files

In [55]:
# repo_user = "yjw1029"
# repo_name = "MIND"
# repo_files = {"train": "MINDsmall_train.zip"}

In [56]:
# List all files in the dataset repository
files = list_repo_files(repo_id="yjw1029/MIND", repo_type="dataset")
for file in files:
    print(file)

.gitattributes
MINDlarge_dev.zip
MINDlarge_test.zip
MINDlarge_train.zip
MINDsmall_dev.zip
MINDsmall_train.zip
README.md

To load data from Hugging Face, you can use the `load_dataset` function from the `datasets` library. You will need to specify the name of the dataset you want to load. For example, to load the 'imdb' dataset, you would use the following code:

In [57]:
import zipfile
import os

# Define the repository details
repo_user = "yjw1029"
repo_name = "MIND"
repo_file = "MINDsmall_train.zip"

# Download the zip file
print(f"Downloading {repo_file} from {repo_user}/{repo_name}...")
local_zip_path = hf_hub_download(repo_id=f"{repo_user}/{repo_name}", filename=repo_file, repo_type="dataset")
print(f"Downloaded to: {local_zip_path}")

# Define extraction path
extract_path = "./MINDsmall_train_data"
os.makedirs(extract_path, exist_ok=True)

# Extract the contents of the zip file
print(f"Extracting {local_zip_path} to {extract_path}...")
with zipfile.ZipFile(local_zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)
print("Extraction complete.")

Downloading MINDsmall_train.zip from yjw1029/MIND...
Downloaded to: /root/.cache/huggingface/hub/datasets--yjw1029--MIND/snapshots/0f871bdfd1ac4029324a48722ec6d52d714ebf27/MINDsmall_train.zip
Extracting /root/.cache/huggingface/hub/datasets--yjw1029--MIND/snapshots/0f871bdfd1ac4029324a48722ec6d52d714ebf27/MINDsmall_train.zip to ./MINDsmall_train_data...
Extraction complete.

Get file list:
- root = > your current root directory
- dirs => folders in root
- name.split(".")[0] ensure the key of extracted_file_list is clean (ie. without 'dangling extension')

In [58]:
# List extracted files to see their structure
extracted_file_list = {}
print("Extracted files:")
for root, dirs, files in os.walk(extract_path):
    for name in files:
        print(os.path.join(root, name))
        extracted_file_list[name.split(".")[0]] = os.path.join(root, name)

#https://huggingface.co/datasets/yjw1029/MIND/resolve/main/MINDsmall_train.zip

# Now you can load individual files. For example, loading behaviors.tsv:
# try:
#     behaviors_df = pd.read_csv(os.path.join(extract_path, 'MINDsmall_train/behaviors.tsv'), sep='\t', header=None, names=['impression_id', 'user_id', 'time', 'history', 'impressions'])
#     print("Behaviors data loaded successfully:")
#     display(behaviors_df.head())
# except FileNotFoundError:
#     print("behaviors.tsv not found in expected path. Please check extracted files.")

# Or using datasets.load_dataset for a specific file:
# try:
#     news_dataset = datasets.load_dataset('csv', data_files=os.path.join(extract_path, 'MINDsmall_train/news.tsv'), sep='\t')
#     print("News data loaded successfully:")
#     display(news_dataset)
# except FileNotFoundError:
#     print("news.tsv not found in expected path. Please check extracted files.")

Extracted files:
./MINDsmall_train_data/MINDsmall_train/entity_embedding.vec
./MINDsmall_train_data/MINDsmall_train/relation_embedding.vec
./MINDsmall_train_data/MINDsmall_train/news.tsv
./MINDsmall_train_data/MINDsmall_train/behaviors.tsv

In [59]:
extracted_file_list

{'entity_embedding': './MINDsmall_train_data/MINDsmall_train/entity_embedding.vec',
 'relation_embedding': './MINDsmall_train_data/MINDsmall_train/relation_embedding.vec',
 'news': './MINDsmall_train_data/MINDsmall_train/news.tsv',
 'behaviors': './MINDsmall_train_data/MINDsmall_train/behaviors.tsv'}

In [60]:
column_dict = {
  'relation_embedding': [],
 'news': ['NewsID', 'Category', 'SubCategory', 'Title', 'Abstract', 'URL', 'TitleEntities', 'AbstractEntities'],
 'entity_embedding': [],
 'behaviors': ['ImpressionID', 'UserID', 'Time', 'History', 'Impressions'],
}

In [61]:
news_df = pd.read_csv(os.path.join(extracted_file_list['news']), sep='\t', header=None)
news_df.columns = column_dict['news']
display(news_df.head(20))

,NewsID,Category,SubCategory,Title,Abstract,URL,TitleEntities,AbstractEntities
0,N55528,lifestyle,lifestyleroyals,"The Brands Queen Elizabeth, Prince Charles, an...","Shop the notebooks, jackets, and more that the...",https://assets.msn.com/labs/mind/AAGH0ET.html,"[{""Label"": ""Prince Philip, Duke of Edinburgh"",...",[]
1,N19639,health,weightloss,50 Worst Habits For Belly Fat,These seemingly harmless habits are holding yo...,https://assets.msn.com/labs/mind/AAB19MK.html,"[{""Label"": ""Adipose tissue"", ""Type"": ""C"", ""Wik...","[{""Label"": ""Adipose tissue"", ""Type"": ""C"", ""Wik..."
2,N61837,news,newsworld,The Cost of Trump's Aid Freeze in the Trenches...,Lt. Ivan Molchanets peeked over a parapet of s...,https://assets.msn.com/labs/mind/AAJgNsz.html,[],"[{""Label"": ""Ukraine"", ""Type"": ""G"", ""WikidataId..."
3,N53526,health,voices,I Was An NBA Wife. Here's How It Affected My M...,"I felt like I was a fraud, and being an NBA wi...",https://assets.msn.com/labs/mind/AACk2N6.html,[],"[{""Label"": ""National Basketball Association"", ..."
4,N38324,health,medical,"How to Get Rid of Skin Tags, According to a De...","They seem harmless, but there's a very good re...",https://assets.msn.com/labs/mind/AAAKEkt.html,"[{""Label"": ""Skin tag"", ""Type"": ""C"", ""WikidataI...","[{""Label"": ""Skin tag"", ""Type"": ""C"", ""WikidataI..."
5,N2073,sports,football_nfl,Should NFL be able to fine players for critici...,Several fines came down against NFL players fo...,https://assets.msn.com/labs/mind/AAJ4lap.html,"[{""Label"": ""National Football League"", ""Type"":...","[{""Label"": ""National Football League"", ""Type"":..."
6,N49186,weather,weathertopstories,It's been Orlando's hottest October ever so fa...,There won't be a chill down to your bones this...,https://assets.msn.com/labs/mind/AAJwoxD.html,"[{""Label"": ""Orlando, Florida"", ""Type"": ""G"", ""W...","[{""Label"": ""Orlando, Florida"", ""Type"": ""G"", ""W..."
7,N59295,news,newsworld,Chile: Three die in supermarket fire amid prot...,Three people have died in a supermarket fire a...,https://assets.msn.com/labs/mind/AAJ43pw.html,"[{""Label"": ""Chile"", ""Type"": ""G"", ""WikidataId"":...","[{""Label"": ""Santiago"", ""Type"": ""G"", ""WikidataI..."
8,N24510,entertainment,gaming,Best PS5 games: top PlayStation 5 titles to lo...,Every confirmed or expected PS5 game we can't ...,https://assets.msn.com/labs/mind/AACHUn8.html,"[{""Label"": ""PlayStation"", ""Type"": ""J"", ""Wikida...",[]
9,N39237,news,newsscienceandtechnology,"How to report weather-related closings, delays","When there are active closings, view them here...",https://assets.msn.com/labs/mind/AAlErhA.html,[],"[{""Label"": ""WXII-TV"", ""Type"": ""M"", ""WikidataId..."
10,N9721,health,nutrition,"50 Foods You Should Never Eat, According to He...",This is so depressing.,https://assets.msn.com/labs/mind/AABDHTv.html,[],[]
11,N60905,autos,autosenthusiasts,Trying to Make a Ram 3500 as Quick as a Viper ...,The 2019 Ram 3500's new Cummins diesel has 100...,https://assets.msn.com/labs/mind/AADKhPQ.html,"[{""Label"": ""Ram Pickup"", ""Type"": ""V"", ""Wikidat...","[{""Label"": ""Ram Pickup"", ""Type"": ""V"", ""Wikidat..."
12,N39758,health,nutrition,25 Biggest Grocery Store Mistakes Making You G...,From picking up free goodies to navigating the...,https://assets.msn.com/labs/mind/AABqkFQ.html,"[{""Label"": ""Weight gain"", ""Type"": ""C"", ""Wikida...",[]
13,N28361,health,wellness,Instagram Filters with Plastic Surgery-Inspire...,In an effort to combat some of the negative me...,https://assets.msn.com/labs/mind/AAJaBOM.html,"[{""Label"": ""Instagram"", ""Type"": ""W"", ""Wikidata...",[]
14,N18680,health,health-news,"Michigan apple recall: Nearly 2,300 crates cou...",A Michigan produce company has recalled nearly...,https://assets.msn.com/labs/mind/AAJwfO8.html,"[{""Label"": ""Michigan"", ""Type"": ""G"", ""WikidataI...","[{""Label"": ""Michigan"", ""Type"": ""G"", ""WikidataI..."
15,N55610,lifestyle,lifestyleroyals,Kate Middleton's Best Hairstyles Through the Y...,The Duchess of Cambridge knows her way around ...,https://assets.msn.com/labs/mind/AAEBVOU.html,"[{""Label"": ""Catherine, Duchess of Cambridge"", ...","[{""Label"": ""Catherine, Duchess of Cambridge"", ..."
16,N35621,entertainment,celebrity,Stars who got fired from major projects,Take a look back at the celebs who got the boo...,https://assets.msn.com/labs/mind/AABv6WU.html,[],[]
17,N22850,travel,travelarticle,Newark Liberty Airport's Terminal One a $2.7 b...,"The project, which is the bi-state agency's si...",https://assets.msn.com/labs/mind/AAJfTqo.html,"[{""Label"": ""Newark Liberty International Airpo...",[]
18,N58173,autos,autossuvs,Is This The 2021 GMC Yukon Denali?,"A Motor1.com reader sent this to us, and it su...",https://assets.msn.com/labs/mind/AAGZhlc.html,"[{""Label"": ""Chevrolet Tahoe"", ""Type"": ""V"", ""Wi...","[{""Label"": ""Motorsport Network"", ""Type"": ""O"", ..."
19,N29120,sports,football_nfl,"John Dorsey admits talks with Washington, but ...","Team officials in Washington ""emphatically"" de...",https://assets.msn.com/labs/mind/AAISxPW.html,"[{""Label"": ""John Dorsey (American football)"", ...","[{""Label"": ""John Dorsey (American football)"", ..."

In [62]:
#URL Links unfortunately are dead,and we âre id'ing the news by NewsID anyway. Hence, remove the URL column.
#Indeed, that is goodbye to seeing the full thing in the URL, which at least save time of training
news_df = news_df.drop(columns=['URL'])
news_df.head(20)

,NewsID,Category,SubCategory,Title,Abstract,TitleEntities,AbstractEntities
0,N55528,lifestyle,lifestyleroyals,"The Brands Queen Elizabeth, Prince Charles, an...","Shop the notebooks, jackets, and more that the...","[{""Label"": ""Prince Philip, Duke of Edinburgh"",...",[]
1,N19639,health,weightloss,50 Worst Habits For Belly Fat,These seemingly harmless habits are holding yo...,"[{""Label"": ""Adipose tissue"", ""Type"": ""C"", ""Wik...","[{""Label"": ""Adipose tissue"", ""Type"": ""C"", ""Wik..."
2,N61837,news,newsworld,The Cost of Trump's Aid Freeze in the Trenches...,Lt. Ivan Molchanets peeked over a parapet of s...,[],"[{""Label"": ""Ukraine"", ""Type"": ""G"", ""WikidataId..."
3,N53526,health,voices,I Was An NBA Wife. Here's How It Affected My M...,"I felt like I was a fraud, and being an NBA wi...",[],"[{""Label"": ""National Basketball Association"", ..."
4,N38324,health,medical,"How to Get Rid of Skin Tags, According to a De...","They seem harmless, but there's a very good re...","[{""Label"": ""Skin tag"", ""Type"": ""C"", ""WikidataI...","[{""Label"": ""Skin tag"", ""Type"": ""C"", ""WikidataI..."
5,N2073,sports,football_nfl,Should NFL be able to fine players for critici...,Several fines came down against NFL players fo...,"[{""Label"": ""National Football League"", ""Type"":...","[{""Label"": ""National Football League"", ""Type"":..."
6,N49186,weather,weathertopstories,It's been Orlando's hottest October ever so fa...,There won't be a chill down to your bones this...,"[{""Label"": ""Orlando, Florida"", ""Type"": ""G"", ""W...","[{""Label"": ""Orlando, Florida"", ""Type"": ""G"", ""W..."
7,N59295,news,newsworld,Chile: Three die in supermarket fire amid prot...,Three people have died in a supermarket fire a...,"[{""Label"": ""Chile"", ""Type"": ""G"", ""WikidataId"":...","[{""Label"": ""Santiago"", ""Type"": ""G"", ""WikidataI..."
8,N24510,entertainment,gaming,Best PS5 games: top PlayStation 5 titles to lo...,Every confirmed or expected PS5 game we can't ...,"[{""Label"": ""PlayStation"", ""Type"": ""J"", ""Wikida...",[]
9,N39237,news,newsscienceandtechnology,"How to report weather-related closings, delays","When there are active closings, view them here...",[],"[{""Label"": ""WXII-TV"", ""Type"": ""M"", ""WikidataId..."
10,N9721,health,nutrition,"50 Foods You Should Never Eat, According to He...",This is so depressing.,[],[]
11,N60905,autos,autosenthusiasts,Trying to Make a Ram 3500 as Quick as a Viper ...,The 2019 Ram 3500's new Cummins diesel has 100...,"[{""Label"": ""Ram Pickup"", ""Type"": ""V"", ""Wikidat...","[{""Label"": ""Ram Pickup"", ""Type"": ""V"", ""Wikidat..."
12,N39758,health,nutrition,25 Biggest Grocery Store Mistakes Making You G...,From picking up free goodies to navigating the...,"[{""Label"": ""Weight gain"", ""Type"": ""C"", ""Wikida...",[]
13,N28361,health,wellness,Instagram Filters with Plastic Surgery-Inspire...,In an effort to combat some of the negative me...,"[{""Label"": ""Instagram"", ""Type"": ""W"", ""Wikidata...",[]
14,N18680,health,health-news,"Michigan apple recall: Nearly 2,300 crates cou...",A Michigan produce company has recalled nearly...,"[{""Label"": ""Michigan"", ""Type"": ""G"", ""WikidataI...","[{""Label"": ""Michigan"", ""Type"": ""G"", ""WikidataI..."
15,N55610,lifestyle,lifestyleroyals,Kate Middleton's Best Hairstyles Through the Y...,The Duchess of Cambridge knows her way around ...,"[{""Label"": ""Catherine, Duchess of Cambridge"", ...","[{""Label"": ""Catherine, Duchess of Cambridge"", ..."
16,N35621,entertainment,celebrity,Stars who got fired from major projects,Take a look back at the celebs who got the boo...,[],[]
17,N22850,travel,travelarticle,Newark Liberty Airport's Terminal One a $2.7 b...,"The project, which is the bi-state agency's si...","[{""Label"": ""Newark Liberty International Airpo...",[]
18,N58173,autos,autossuvs,Is This The 2021 GMC Yukon Denali?,"A Motor1.com reader sent this to us, and it su...","[{""Label"": ""Chevrolet Tahoe"", ""Type"": ""V"", ""Wi...","[{""Label"": ""Motorsport Network"", ""Type"": ""O"", ..."
19,N29120,sports,football_nfl,"John Dorsey admits talks with Washington, but ...","Team officials in Washington ""emphatically"" de...","[{""Label"": ""John Dorsey (American football)"", ...","[{""Label"": ""John Dorsey (American football)"", ..."

In [63]:
news_df.iloc[55]

NewsID                                                         N40045
Category                                                       travel
SubCategory                                                travelnews
Title               Tim Burton's Original Art Is on Display at the...
Abstract            A rare retrospective dedicated to the filmmake...
TitleEntities       [{"Label": "Tim Burton", "Type": "P", "Wikidat...
AbstractEntities    [{"Label": "United States", "Type": "G", "Wiki...
Name: 55, dtype: object

In [64]:
example = news_df[['TitleEntities','AbstractEntities']].iloc[55]
example.AbstractEntities

'[{"Label": "United States", "Type": "G", "WikidataId": "Q30", "Confidence": 0.981, "OccurrenceOffsets": [152], "SurfaceForms": ["United States"]}]'

In [65]:
# {'relation_embedding': './MINDsmall_train_data/MINDsmall_train/relation_embedding.vec',
#  'news': './MINDsmall_train_data/MINDsmall_train/news.tsv',
#  'entity_embedding': './MINDsmall_train_data/MINDsmall_train/entity_embedding.vec',
#  'behaviors': './MINDsmall_train_data/MINDsmall_train/behaviors.tsv'}
relation_df = pd.read_csv(os.path.join(extracted_file_list['relation_embedding']), sep='\t', header=None)
display(relation_df)

,0,1,2,3,4,5,6,7,8,9,...,92,93,94,95,96,97,98,99,100,101
0,P31,-0.073467,-0.132227,0.034173,-0.032769,0.008289,-0.107088,-0.031712,-0.039581,0.101882,...,-0.050068,-0.053686,-0.045389,-0.037017,0.117190,-0.063597,-0.056910,0.058387,-0.114056,NaN
1,P21,-0.078436,0.108589,-0.049429,-0.131355,0.049300,-0.094605,-0.101469,0.127802,-0.081245,...,0.074341,-0.030571,-0.137183,0.045598,-0.151155,-0.066223,0.057489,0.130188,-0.054801,NaN
2,P106,-0.052137,0.052444,-0.019886,-0.152309,0.014144,-0.180491,-0.132198,0.063082,0.085229,...,-0.058958,-0.032021,-0.147213,0.082776,-0.169705,0.122445,-0.054737,0.055321,0.070961,NaN
3,P735,-0.051398,0.056219,0.068029,-0.137717,-0.030050,0.061566,-0.103184,-0.074124,-0.118975,...,-0.092234,0.056870,0.013640,0.042696,0.013683,-0.021127,-0.189257,0.055315,0.101863,NaN
4,P108,0.091231,0.022526,0.059349,-0.141853,0.035025,-0.111040,-0.127337,0.047645,-0.172328,...,-0.046994,-0.056248,-0.146538,0.121375,-0.211757,0.077591,-0.002200,-0.053880,0.140873,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1086,P1897,-0.019021,0.001183,-0.009602,-0.040833,-0.026919,-0.000777,-0.008379,0.002261,-0.010804,...,-0.032050,-0.002357,-0.049197,-0.023061,-0.027072,0.035122,-0.006339,-0.028845,-0.005709,NaN
1087,P3776,-0.018365,0.028526,-0.025934,0.032296,-0.015580,-0.012719,-0.009017,0.006737,-0.001155,...,-0.006468,-0.006864,0.004695,-0.015650,0.031345,-0.008722,0.024273,0.001479,0.032974,NaN
1088,P1194,-0.026819,0.003231,-0.011298,-0.015206,0.013172,-0.033084,0.026422,-0.005384,0.033045,...,-0.002927,-0.013136,0.018877,-0.015216,-0.006110,0.013847,-0.002365,0.034509,-0.003884,NaN
1089,P2502,0.003554,-0.041121,-0.010559,-0.037862,-0.003736,-0.002184,-0.015868,0.029463,0.023216,...,0.020671,-0.011002,0.041005,-0.022877,-0.055011,0.002874,-0.014109,-0.012319,-0.004955,NaN
1090,P6977,-0.023617,-0.021648,0.009369,-0.021757,0.020885,-0.020526,-0.027134,0.005834,0.026317,...,-0.023417,0.013911,-0.007208,0.012723,-0.008430,-0.005681,0.022748,-0.018340,0.006243,NaN

In [66]:
entity_df = pd.read_csv(os.path.join(extracted_file_list['entity_embedding']), sep='\t', header=None)
display(entity_df)

,0,1,2,3,4,5,6,7,8,9,...,92,93,94,95,96,97,98,99,100,101
0,Q41,-0.063388,-0.181451,0.057501,-0.091254,-0.076217,-0.052525,0.050500,-0.224871,-0.018145,...,0.001861,0.124535,-0.151043,-0.263698,-0.103607,0.020007,-0.101157,-0.091567,0.035234,NaN
1,Q1860,0.060958,0.069934,0.015832,0.079471,-0.023362,-0.125007,-0.043618,0.134063,-0.121691,...,-0.014287,0.013578,0.099977,0.012199,-0.141138,0.056129,-0.133727,0.025795,0.051448,NaN
2,Q39631,-0.093106,-0.052002,0.020556,-0.020801,0.043180,-0.072321,0.000910,0.028156,0.176303,...,-0.086840,-0.078992,-0.062712,0.051117,-0.184307,0.127637,-0.144866,0.044690,0.013498,NaN
3,Q30,-0.115737,-0.179113,0.102739,-0.112469,-0.101853,-0.177516,0.015860,-0.092626,0.086708,...,0.080511,-0.000085,-0.089968,-0.083486,-0.149992,-0.053031,-0.136071,-0.029001,0.174155,NaN
4,Q60,-0.051036,-0.165637,0.132802,-0.089949,-0.146637,-0.142246,0.103853,-0.129651,0.096265,...,0.078628,0.003711,-0.058953,-0.154067,-0.117159,-0.031614,-0.140451,0.001288,0.140350,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26899,Q42225228,-0.051346,-0.028947,-0.075870,0.017512,-0.066910,-0.027968,0.020820,0.089614,-0.024825,...,-0.024313,0.034771,0.044909,0.043314,-0.020466,-0.009811,0.028233,-0.015396,0.063876,NaN
26900,Q54860678,-0.031620,-0.041283,-0.016871,0.044251,-0.022709,0.014341,0.034043,0.018170,0.002922,...,0.033638,0.070052,0.043695,-0.060374,0.036932,-0.014621,0.048494,-0.029104,0.057286,NaN
26901,Q54860790,0.034682,-0.009413,-0.024317,0.073895,0.028052,0.028039,0.039260,0.017398,0.017743,...,0.034473,0.035736,0.008329,-0.049981,-0.025212,-0.018404,0.004110,0.013771,-0.008027,NaN
26902,Q54862508,-0.052323,-0.078029,-0.060925,-0.052536,0.006802,-0.070488,-0.081736,0.026385,-0.037127,...,0.045298,0.009842,-0.019821,-0.033952,-0.047436,0.062752,0.043236,0.032251,-0.001261,NaN
26903,Q42301562,-0.005190,-0.047871,0.009753,-0.021500,-0.000049,-0.010786,0.031302,0.022225,-0.022653,...,-0.014884,0.047493,0.060764,0.013757,0.026994,0.016827,0.024246,-0.040823,-0.008903,NaN

In [67]:
behavior_df = pd.read_csv(os.path.join(extracted_file_list['behaviors']), sep='\t', header=None)
behavior_df.columns = column_dict['behaviors']
display(behavior_df)

,ImpressionID,UserID,Time,History,Impressions
0,1,U13740,11/11/2019 9:05:58 AM,N55189 N42782 N34694 N45794 N18445 N63302 N104...,N55689-1 N35729-0
1,2,U91836,11/12/2019 6:11:30 PM,N31739 N6072 N63045 N23979 N35656 N43353 N8129...,N20678-0 N39317-0 N58114-0 N20495-0 N42977-0 N...
2,3,U73700,11/14/2019 7:01:48 AM,N10732 N25792 N7563 N21087 N41087 N5445 N60384...,N50014-0 N23877-0 N35389-0 N49712-0 N16844-0 N...
3,4,U34670,11/11/2019 5:28:05 AM,N45729 N2203 N871 N53880 N41375 N43142 N33013 ...,N35729-0 N33632-0 N49685-1 N27581-0
4,5,U8125,11/12/2019 4:11:21 PM,N10078 N56514 N14904 N33740,N39985-0 N36050-0 N16096-0 N8400-1 N22407-0 N6...
...,...,...,...,...,...
156960,156961,U21593,11/14/2019 10:24:05 PM,N7432 N58559 N1954 N43353 N14343 N13008 N28833...,N2235-0 N22975-0 N64037-0 N47652-0 N11378-0 N4...
156961,156962,U10123,11/13/2019 6:57:04 AM,N9803 N104 N24462 N57318 N55743 N40526 N31726 ...,N3841-0 N61571-0 N58813-0 N28213-0 N4428-0 N25...
156962,156963,U75630,11/14/2019 10:58:13 AM,N29898 N59704 N4408 N9803 N53644 N26103 N812 N...,N55913-0 N62318-0 N53515-0 N10960-0 N9135-0 N5...
156963,156964,U44625,11/13/2019 2:57:02 PM,N4118 N47297 N3164 N43295 N6056 N38747 N42973 ...,N6219-0 N3663-0 N31147-0 N58363-0 N4107-0 N457...
156964,156965,U64800,11/14/2019 3:25:49 PM,N22997 N48742,N61233-0 N33828-1 N19661-0 N41934-0

In [68]:
from google.colab import drive
drive.mount('/content/drive')

# Create the MIND folder if it doesn't exist
path = "/content/drive/MyDrive/MIND"
os.makedirs(path, exist_ok=True)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [69]:
extracted_path_df = pd.DataFrame(extracted_file_list, index=[0])
extracted_path_df.to_csv(os.path.join(path, 'extracted_path.csv'), index=False)

In [70]:
column_name_csv = []
for key, value in column_dict.items():
    column_str = ", ".join(value) if isinstance(value, list) else ""
    column_name_csv.append({'File_Name': key, 'Columns': column_str})

In [71]:
column_name_df = pd.DataFrame(column_name_csv)
# column_name_df.to_csv(os.path.join(path, 'column_name.csv'), index=False)
column_name_df

            File_Name                                            Columns
0  relation_embedding
1                news  NewsID, Category, SubCategory, Title, Abstract...
2    entity_embedding
3           behaviors   ImpressionID, UserID, Time, History, Impressions

In [72]:
#save_path = '/content/drive/MyDrive/MIND/column_mapping.csv'
save_path_col = os.path.join(path, 'column_name.csv')
save_path_extracted_file_name = os.path.join(path, 'extracted_path_name.csv')
extracted_path_df.to_csv(save_path_extracted_file_name, index=False)
column_name_df.to_csv(save_path_col, index=False)

###EDA IN DETAILS

In [73]:
news_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51282 entries, 0 to 51281
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   NewsID            51282 non-null  object
 1   Category          51282 non-null  object
 2   SubCategory       51282 non-null  object
 3   Title             51282 non-null  object
 4   Abstract          48616 non-null  object
 5   TitleEntities     51279 non-null  object
 6   AbstractEntities  51278 non-null  object
dtypes: object(7)
memory usage: 2.7+ MB

In [74]:
news_df['Category'].value_counts()

Category
news             15774
sports           14510
finance           3107
foodanddrink      2551
lifestyle         2479
travel            2350
video             2068
weather           2048
health            1885
autos             1639
tv                 889
music              769
movies             606
entertainment      587
kids                17
middleeast           2
northamerica         1
Name: count, dtype: int64

In [75]:
news_df['SubCategory'].value_counts()

SubCategory
newsus                6564
football_nfl          5420
newspolitics          2826
newscrime             2254
weathertopstories     2047
                      ...
northamerica-video       1
autosmidsize             1
entertainmenttv          1
autoslosangeles          1
celebhub                 1
Name: count, Length: 264, dtype: int64

# Task
Build an Item-to-Item news recommendation system using the MIND dataset located at "./MINDsmall_train_data/MINDsmall_train/". The system should follow a content-based filtering approach where, given a source article (NewsID), it recommends 5 articles based on the logic "Because you liked X, you may like Y".

The implementation must include:
1.  **Feature Engineering**: Utilize 'Category', 'SubCategory', and text features from 'Title' and 'Abstract' in `news_df`.
2.  **Similarity Engine**: Compute item embeddings using TF-IDF vectors on text or by leveraging the provided `entity_embedding.vec` and `relation_embedding.vec` to calculate Cosine Similarity.
3.  **Diversity Mechanism**: Implement a retrieval logic (e.g., Maximal Marginal Relevance) to return 5 items, ensuring a balance between 3-4 highly similar articles and 1-2 peripheral articles from related SubCategories to encourage discovery.
4.  **Inference Pipeline**: Create a function that takes a NewsID as input and returns the top 5 recommendations using a pre-computed similarity index (or an ANN index like FAISS).
5.  **Validation**: Use `behavior_df` to verify if the recommended items appear in the same user sessions or click histories for a sample of users.

## Define Recommendation Strategy

### Subtask:
Outline the Item-to-Item Content-Based Filtering strategy and map out how features from news_df will be used to derive recommendations.

### Recommendation Strategy: Item-to-Item Content-Based Filtering

#### 1. Core Logic
The **Item-to-Item Content-Based Filtering** approach identifies similar articles based on their inherent attributes rather than user-item interaction history. By calculating the similarity between items, we can recommend news that shares common characteristics with articles a user has previously engaged with.

#### 2. Feature Mapping from `news_df`
We will leverage the following features to compute similarity:
- **Category & SubCategory:** Provide high-level thematic alignment (e.g., both articles are about 'sports/football_nfl').
- **Title:** The primary textual representation of the article's core topic.
- **Abstract:** Provides deeper context and detailed keywords not present in the title.

#### 3. Semantic Context via Entities
- **TitleEntities & AbstractEntities:** These fields contain linked entities (e.g., specific people, organizations, or locations). By using these, we can move beyond simple keyword matching and calculate similarity based on shared entities (e.g., both articles mention 'Tim Burton'), providing a more accurate semantic representation of the content.

#### 4. 'Because you liked X, you may like Y' Logic
For a given article **X**, the system will identify a candidate article **Y** if:
- **Feature Overlap:** Y belongs to the same `Category` or `SubCategory` as X.
- **Embedding Proximity:** The textual features (Title/Abstract) of Y have a high cosine similarity score compared to X, potentially using the provided `entity_embedding` to represent the entities found within the text.

## Algorithm Selection for Item Similarity

### Subtask:
Develop the logic to compute item embeddings and calculate similarity scores between news articles.

**Reasoning**:
I will start by processing the textual features from news_df, concatenating Title and Abstract while handling missing values, and then vectorizing the text using TF-IDF.

In [76]:
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np

# 1. Process textual features: Concatenate Title and Abstract, handle NaNs
news_df['Title'] = news_df['Title'].fillna('')
news_df['Abstract'] = news_df['Abstract'].fillna('')
news_df['CombinedText'] = news_df['Title'] + " " + news_df['Abstract']

# 2. Transform text into TF-IDF matrix
tfidf = TfidfVectorizer(stop_words='english', max_features=5000)
tfidf_matrix = tfidf.fit_transform(news_df['CombinedText'])

print(f'TF-IDF matrix shape: {tfidf_matrix.shape}')
news_df[['NewsID', 'CombinedText']].head()

TF-IDF matrix shape: (51282, 5000)

   NewsID                                       CombinedText
0  N55528  The Brands Queen Elizabeth, Prince Charles, an...
1  N19639  50 Worst Habits For Belly Fat These seemingly ...
2  N61837  The Cost of Trump's Aid Freeze in the Trenches...
3  N53526  I Was An NBA Wife. Here's How It Affected My M...
4  N38324  How to Get Rid of Skin Tags, According to a De...

**Reasoning**:
I will now develop the method to represent each article as a weighted vector based on the entity embeddings from entity_df and the entities found in the 'TitleEntities' and 'AbstractEntities' columns.

In [77]:
import json

# Prepare entity embeddings dictionary for fast lookup
# entity_df has ID in column 0 and embeddings in columns 1 to 100
entity_embeddings_dict = entity_df.set_index(0).T.to_dict('list')
embedding_dim = entity_df.shape[1] - 1

def get_article_entity_embedding(row):
    entities = []
    # Parse TitleEntities and AbstractEntities
    for col in ['TitleEntities', 'AbstractEntities']:
        val = row[col]
        if isinstance(val, str) and val.strip():
            try:
                entity_list = json.loads(val)
                for ent in entity_list:
                    entities.append(ent.get('WikidataId'))
            except json.JSONDecodeError:
                continue

    # Filter valid embeddings
    valid_vectors = [np.array(entity_embeddings_dict[eid]) for eid in entities if eid in entity_embeddings_dict]

    if not valid_vectors:
        return np.zeros(embedding_dim)

    return np.mean(valid_vectors, axis=0)

print("Calculating entity-based embeddings for articles...")
# Apply the function to each row
news_entity_embeddings = np.stack(news_df.apply(get_article_entity_embedding, axis=1).values)

print(f'Entity embedding matrix shape: {news_entity_embeddings.shape}')

Calculating entity-based embeddings for articles...
Entity embedding matrix shape: (51282, 101)

**Reasoning**:
I will now implement a function to calculate cosine similarity for both TF-IDF and entity-based embeddings, then combine them using a weighted average to generate a final similarity score between a source article and all others.

In [78]:
from sklearn.metrics.pairwise import cosine_similarity

# Handle NaNs in entity embeddings (replace with 0 if any mean calculation resulted in NaN)
news_entity_embeddings = np.nan_to_num(news_entity_embeddings)

def get_hybrid_similarities(news_id, tfidf_mtx, entity_mtx, df, alpha=0.5):
    # Get the index of the source article
    try:
        idx = df[df['NewsID'] == news_id].index[0]
    except IndexError:
        return None

    # 1. Text-based similarity (TF-IDF)
    text_sim = cosine_similarity(tfidf_mtx[idx], tfidf_mtx).flatten()

    # 2. Entity-based similarity
    entity_sim = cosine_similarity(entity_mtx[idx].reshape(1, -1), entity_mtx).flatten()

    # 3. Combined similarity (Weighted Average)
    combined_sim = (alpha * text_sim) + ((1 - alpha) * entity_sim)

    return combined_sim

# Example usage for one NewsID
test_news_id = news_df['NewsID'].iloc[0]
similarities = get_hybrid_similarities(test_news_id, tfidf_matrix, news_entity_embeddings, news_df)
print(f'Similarity scores calculated for {test_news_id}. Shape: {similarities.shape}')

Similarity scores calculated for N55528. Shape: (51282,)

## Mechanism for Peripheral Recommendations

### Subtask:
Implement a selection logic to retrieve 5 items for a given NewsID, including a diversity mechanism (MMR) and category-based exploration.

**Reasoning**:
I will implement the MMR-based retrieval function along with category-based exploration to select exactly 5 unique news recommendations for a given NewsID.

In [79]:
def calculate_mmr(similarities, tfidf_mtx, candidate_indices, top_k=3, lambd=0.7):
    """Maximal Marginal Relevance selection."""
    selected_indices = [candidate_indices[0]]
    remaining_indices = candidate_indices[1:]

    while len(selected_indices) < top_k and remaining_indices:
        mmr_scores = []
        for idx in remaining_indices:
            sim_to_query = similarities[idx]
            # Calculate max similarity to already selected items using TF-IDF
            sim_to_selected = cosine_similarity(tfidf_mtx[idx], tfidf_mtx[selected_indices]).max()
            score = lambd * sim_to_query - (1 - lambd) * sim_to_selected
            mmr_scores.append(score)

        best_idx = remaining_indices.pop(np.argmax(mmr_scores))
        selected_indices.append(best_idx)
    return selected_indices

def recommend_news(news_id, df, tfidf_mtx, entity_mtx, top_n_candidates=50):
    # 1. Get hybrid similarities
    sims = get_hybrid_similarities(news_id, tfidf_mtx, entity_mtx, df)
    if sims is absent:
        return []

    source_idx = df[df['NewsID'] == news_id].index[0]
    source_row = df.iloc[source_idx]

    # 2. Get top candidates (excluding source itself)
    candidate_indices = np.argsort(sims)[::-1]
    candidate_indices = [i for i in candidate_indices if i != source_idx][:top_n_candidates]

    # 3. Select 3-4 highly similar articles using MMR
    highly_similar_indices = calculate_mmr(sims, tfidf_mtx, candidate_indices, top_k=3, lambd=0.7)

    # 4. Select 1-2 peripheral articles: same Category, different SubCategory
    peripheral_candidates = df[(df['Category'] == source_row['Category']) &
                               (df['SubCategory'] != source_row['SubCategory'])].index.tolist()
    # Exclude source and already selected
    peripheral_candidates = [i for i in peripheral_candidates if i != source_idx and i not in highly_similar_indices]

    # Sort peripheral by similarity
    if peripheral_candidates:
        peripheral_candidates = sorted(peripheral_candidates, key=lambda x: sims[x], reverse=True)
        peripheral_indices = peripheral_candidates[:2]
    else:
        # Fallback if no specific peripheral found
        peripheral_indices = [i for i in candidate_indices if i not in highly_similar_indices][:2]

    # Combine and ensure exactly 5
    final_indices = highly_similar_indices + peripheral_indices
    return df.iloc[final_indices][['NewsID', 'Title', 'Category', 'SubCategory']]

# Test the function
sample_id = news_df['NewsID'].iloc[55]
print(f"Recommendations for: {news_df[news_df['NewsID']==sample_id]['Title'].values[0]} ({news_df[news_df['NewsID']==sample_id]['SubCategory'].values[0]})\n")
recs = recommend_news(sample_id, news_df, tfidf_matrix, news_entity_embeddings)
display(recs)

Recommendations for: Tim Burton's Original Art Is on Display at the Neon Museum in Las Vegas (travelnews)

NameError: name 'absent' is not defined